default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: iama_app
  password: "Frajola.69"
  host: node267478-env-1396074.sp1.br.saveincloud.net.br
  database: iama-production

