default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
  # adapter: mysql2
  # encoding: utf8
  # database: iama-production
  # username: root
  # password: <%= ENV['IAMA_DATABASE_PASSWORD'] %>
