default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  host: mysql88570-clinicaiama.jelasticlw.com.br
  password: YDItyd07983
  database: iama-production

