# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  locastyle:
    css:   "http://assets.locaweb.com.br/locastyle/3.2.2/stylesheets/locastyle.css"
    js:    "http://assets.locaweb.com.br/locastyle/3.2.2/javascripts/locastyle.js"

  site:
    name: Clinica Iama
    title: Clinica Iama
    domain: clinicaiama.com.br
    url: http://www.clinicaiama.com.br
    email: clinicaiama@clinicaiama.com.br

development: &development
  <<: *default
  secret_key_base: 6ca1a6741990c754cb3a8bf135b5e8024121a589371f8de3b9c9cf2c505f486f3b4ff9c67a9bcc6c7daf3a9fc15bf454a1dcb74673b846934feee07c05b2caff

test:
  <<: *default
  secret_key_base: cb762d2d061acc715a12defffb1eb0b69310849fd1c6cf4d490f0e394abb3315b6d0d91dba429a379f43235c8a145200668f5b9428d4ba46399cf658abcb59c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
