# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
puts 'Creating Role...'
['registered', 'moderator', 'admin'].each do |role|
  Role.find_or_create_by({name: role})
end

puts 'Creating User Admin...'
User.create! :name => "admin", :email => "admin@admin.com", :password => "inicial1234", :role_id => 3

puts 'Tests'
puts 'Creating Surgeon for test...'
Surgeon.find_or_create_by({:name => "André Lucas", :cpf => "71155072871", :phone => "159990987", :email => "teste@teste.com", :address => "Rua Portugues", :address_number => "1", :address_complement => "1", :district => "Simus", :city => "Sorocaba", :postal_code => "18440000", :state => "SP"})
Surgeon.find_or_create_by({:name => "Pakita", :cpf => "67770445230", :phone => "15987654", :email => "www@teste.com", :address => "Alamenda Portugues", :address_number => "2", :address_complement => "1", :district => "Tiete", :city => "Ita", :postal_code => "18440000", :state => "SP"})
Surgeon.find_or_create_by({:name => "Dé", :cpf => "40062472143", :phone => "1543678", :email => "qqqqq@teste.com", :address => "Avenida Ingles", :address_number => "3", :address_complement => "1", :district => "Flora", :city => "Itapopoca", :postal_code => "18440000", :state => "SP"})

puts 'Creating Anesthetists for test...'
Anesthetist.find_or_create_by({:name => "Markito", :cpf => "71155072871", :phone => "159987987", :email => "teste@teste.com", :address => "Rua de Teste", :address_number => "1", :address_complement => "1", :district => "Simus", :city => "Sorocaba", :postal_code => "18440000", :state => "SP"})
Anesthetist.find_or_create_by({:name => "José", :cpf => "67770445230", :phone => "1598854", :email => "www@teste.com", :address => "Alamenda das Angelicas", :address_number => "2", :address_complement => "1", :district => "Tiete", :city => "Ita", :postal_code => "18440000", :state => "SP"})
Anesthetist.find_or_create_by({:name => "Vicentino", :cpf => "40062472143", :phone => "15434678", :email => "qqqqq@teste.com", :address => "Avenida General", :address_number => "3", :address_complement => "1", :district => "Flora", :city => "Itapopoca", :postal_code => "18440000", :state => "SP"})

puts 'Creating Patients for test...'
Patient.find_or_create_by({:name => "Paciente 1", :cpf => "71155072871", :phone => "15998987", :email => "teste@teste.com", :address => "Rua 7 de setembro", :address_number => "1", :address_complement => "1", :district => "Simus", :city => "Sorocaba", :postal_code => "18440000", :state => "SP"})
Patient.find_or_create_by({:name => "Paciente 2", :cpf => "67770445230", :phone => "1598854", :email => "www@teste.com", :address => "Alamenda das Angelicas", :address_number => "2", :address_complement => "1", :district => "Tiete", :city => "Ita", :postal_code => "18440000", :state => "SP"})
Patient.find_or_create_by({:name => "Paciente 3", :cpf => "40062472143", :phone => "15432678", :email => "qqqqq@teste.com", :address => "Avenida Padrão", :address_number => "3", :address_complement => "1", :district => "Flora", :city => "Itapopoca", :postal_code => "18440000", :state => "SP"})

puts 'Creating Hospitals for test...'
Hospital.find_or_create_by({:name => "Hospital Santa Casa", :kind => "tipo 1", :status => true})
Hospital.find_or_create_by({:name => "Hospital Unimed", :kind => "tipo 1", :status => false})
Hospital.find_or_create_by({:name => "Hospital Modelo", :kind => "tipo 2", :status => true})

puts 'Creating Bedroons for test...'
Bedroom.find_or_create_by({:name => "Quarto 1", :hospital_id => 1})
Bedroom.find_or_create_by({:name => "Quarto 2", :hospital_id => 1})
Bedroom.find_or_create_by({:name => "Quarto 3", :hospital_id => 1})
Bedroom.find_or_create_by({:name => "Quarto 1", :hospital_id => 2})
Bedroom.find_or_create_by({:name => "Quarto 2", :hospital_id => 2})
Bedroom.find_or_create_by({:name => "Quarto 3", :hospital_id => 2})
Bedroom.find_or_create_by({:name => "Quarto 1", :hospital_id => 3})
Bedroom.find_or_create_by({:name => "Quarto 2", :hospital_id => 3})
Bedroom.find_or_create_by({:name => "Quarto 3", :hospital_id => 3})

puts 'Creating Health insureces for test...'
HealthInsurance.find_or_create_by({:name => "Unimed", :kind => "tipo 1", :status => true})
HealthInsurance.find_or_create_by({:name => "Teste", :kind => "tipo 1", :status => false})
HealthInsurance.find_or_create_by({:name => "Maritima", :kind => "tipo 2", :status => true})

puts 'Creating Size Surgery for test...'
SizeSurgery.find_or_create_by({:health_insurance_id => 1, :size => 1, :value => 10})
SizeSurgery.find_or_create_by({:health_insurance_id => 1, :size => 2, :value => 20})
SizeSurgery.find_or_create_by({:health_insurance_id => 1, :size => 3, :value => 30})
SizeSurgery.find_or_create_by({:health_insurance_id => 2, :size => 1, :value => 10})
SizeSurgery.find_or_create_by({:health_insurance_id => 2, :size => 2, :value => 20})
SizeSurgery.find_or_create_by({:health_insurance_id => 2, :size => 3, :value => 30})
SizeSurgery.find_or_create_by({:health_insurance_id => 3, :size => 1, :value => 10})
SizeSurgery.find_or_create_by({:health_insurance_id => 3, :size => 2, :value => 20})
SizeSurgery.find_or_create_by({:health_insurance_id => 3, :size => 3, :value => 30})

puts 'Creating Health Terminologies for test...'
HealthTerminology.find_or_create_by({:code_tuss => 20102011, :description_tuss => "Holter De 24 Horas - 2 Ou Mais Canais - Analógico", :category_tuss => "Procedimentos Clínicos", :size => 0, :conv => 1 })
HealthTerminology.find_or_create_by({:code_tuss => 20102038, :description_tuss => "Monitorização Ambulatorial Da Pressão Arterial - Mapa (24 Horas)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20102070, :description_tuss => "Tilt Teste", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20102089, :description_tuss => "Sistema Holter - 12 Horas - 1 Canal", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103018, :description_tuss => "Adaptação E Treinamento De Recursos Ópticos Para Visão Subnormal (Por Sessão) -", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103026, :description_tuss => "Amputação Bilateral (Preparação Do Coto)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103034, :description_tuss => "Amputação Bilateral (Treinamento Protético)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103042, :description_tuss => "Amputação Unilateral (Preparação Do Coto)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103050, :description_tuss => "Amputação Unilateral (Treinamento Protético)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103069, :description_tuss => "Assistência Fisiátrica Respiratória Em Pré E Pós-Operatório De Condições Cirúrgicas", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103077, :description_tuss => "Ataxias", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103093, :description_tuss => "Atendimento Fisiátrico No Pré E Pós-Operatório De Pacientes Para Prevenção De", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103107, :description_tuss => "Atendimento Fisiátrico No Pré E Pós-Parto", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103115, :description_tuss => "Atividade Reflexa Ou Aplicação De Técnica Cinesioterápica Específica", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103131, :description_tuss => "Biofeedback Com Emg", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103140, :description_tuss => "Bloqueio Fenólico, Alcoólico Ou Com Toxina Botulínica (De Pontos Motores) - Por Membro", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103182, :description_tuss => "Desvios Posturais Da Coluna Vertebral", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103425, :description_tuss => "Paralisia Cerebral", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103433, :description_tuss => "Paralisia Cerebral Com Distúrbio De Comunicação", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103441, :description_tuss => "Paraparesia/Tetraparesia", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103450, :description_tuss => "Paraplegia E Tetraplegia", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103468, :description_tuss => "Parkinson", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103476, :description_tuss => "Patologia Neurológica Com Dependência De Atividades Da Vida Diária", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103484, :description_tuss => "Patologia Osteomioarticular Em Um Membro", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103492, :description_tuss => "Patologia Osteomioarticular Em Dois Ou Mais Membros", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103506, :description_tuss => "Patologia Osteomioarticular Em Um Segmento Da Coluna", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103514, :description_tuss => "Patologia Osteomioarticular Em Diferentes Segmentos Da Coluna", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103530, :description_tuss => "Recuperação Funcional Pós-Operatória Ou Por Imobilização Da Patologia Vertebral", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103565, :description_tuss => "Processos Inflamatórios Pélvicos", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103611, :description_tuss => "Queimados - Seguimento Ambulatorial Para Prevenção De Seqüelas (Por Segmento)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103620, :description_tuss => "Reabilitação De Paciente Com Endoprótese", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103638, :description_tuss => "Reabilitação Labiríntica (Por Sessão)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103654, :description_tuss => "Recuperação Funcional De Distúrbios Crânio-Faciais", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103662, :description_tuss => "Recuperação Funcional Pós-Operatória Ou Pós-Imobilização Gessada De  Patologia", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103670, :description_tuss => "Recuperação Funcional Pós-Operatória Ou Pós-Imobilização Gessada De  Patologia", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103689, :description_tuss => "Retardo Do Desenvolvimento Psicomotor", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103697, :description_tuss => "Seqüelas De Traumatismos Torácicos E Abdominais", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103719, :description_tuss => "Sinusites", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20103727, :description_tuss => "Reabilitação Cardíaca Supervisionada. Programa De 12 Semanas. Duas A Três Sessões", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104014, :description_tuss => "Actinoterapia (Por Sessão)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104022, :description_tuss => "Aplicação De Hipossensibilizante - Em Consultório (Ahc) Exclusive O Alérgeno -", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104049, :description_tuss => "Cateterismo Vesical Em Retenção Urinária", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104065, :description_tuss => "Cerumen - Remoção (Bilateral)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104073, :description_tuss => "Crioterapia (Grupo De Até 5 Lesões)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104081, :description_tuss => "Curativos Em Geral Com Anestesia, Exceto Queimados", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104090, :description_tuss => "Curativo De Extremidades De Origem Vascular", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104103, :description_tuss => "Curativos Em Geral Sem Anestesia, Exceto Queimados", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104111, :description_tuss => "Dilatação Uretral (Sessão)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104120, :description_tuss => "Fototerapia Com Uva (Puva) (Por Sessão)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104138, :description_tuss => "Imunoterapia Específica - 30 Dias - Planejamento Técnico", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104146, :description_tuss => "Imunoterapia Inespecífica - 30 Dias - Planejamento Técnico", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104154, :description_tuss => "Instilação Vesical Ou Uretral", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104189, :description_tuss => "Sessão De Oxigenoterapia Hiperbárica (Por Sessão De 2 Horas)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104235, :description_tuss => "Terapia Inalatória - Por Nebulização", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104251, :description_tuss => "Terapia Oncológica Com Altas Doses - Por Dia Subseqüente De Tratamento", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104260, :description_tuss => "Terapia Oncológica Com Aplicação De Medicamentos Por Via Intracavitária Ou Intratecal  -", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104286, :description_tuss => "Terapia Oncológica Com Aplicação Intra-Arterial Ou Intravenosa De Medicamentos Em", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104294, :description_tuss => "Terapia Oncológica - Planejamento E 1º Dia De Tratamento", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104308, :description_tuss => "Terapia Oncológica - Por Dia Subseqüente De Tratamento", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104316, :description_tuss => "Curativo De Ouvido (Cada)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104324, :description_tuss => "Curativos Oftalmológicos", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104367, :description_tuss => "Pneumoperitônio (Por Sessão)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20104375, :description_tuss => "Pneumotórax Artificial", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20201010, :description_tuss => "Acompanhamento Clínico De Transplante Renal No Período De Internação Do Receptor E", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20201036, :description_tuss => "Assistência Cardiológica Peroperatória Em Cirurgia Geral E Em Parto (Primeira Hora)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20201044, :description_tuss => "Assistência Cardiológica Peroperatória Em Cirurgia Geral E Em Parto (Horas", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20201052, :description_tuss => "Cardioversão Elétrica Eletiva (Avaliação Clínica, Eletrocardiográfica, Indispensável À", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20201060, :description_tuss => "Rejeição De Enxerto Renal - Tratamento Internado - Avaliação Clínica Diária - Por Visita", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20201079, :description_tuss => "Transplante Duplo Rim-Pâncreas - Acompanhamento Clínico (Pós-Operatório Até 15 Dias)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20201087, :description_tuss => "Tratamento  Conservador  De  Traumatismo  Cranioencefálico, Hipertensão  Intracraniana", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20201095, :description_tuss => "Assistência Cardiológica No Pós-Operatório De Cirurgia Cardíaca (Após A Alta Da Uti)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20201109, :description_tuss => "Avaliação Clínica Diária Enteral", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20201117, :description_tuss => "Avaliação Clínica Diária Parenteral", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20202016, :description_tuss => "Cardiotocografia Anteparto", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20202024, :description_tuss => "Cardiotocografia Intraparto (Por Hora) Até 6 Horas Externa", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20202032, :description_tuss => "Monitorização Hemodinâmica Invasiva (Por 12 Horas)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20202067, :description_tuss => "Monitorização Da Pressão Intracraniana (Por Dia)", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20203012, :description_tuss => "Assistência Fisiátrica Respiratória Em Paciente Internado Com Ventilação Mecânica", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20203020, :description_tuss => "Eletroestimulação Do Assoalho Pélvico E/Ou Outra Técnica De Exercícios Perineais - Por", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20203047, :description_tuss => "Assistência Fisiátrica Respiratória Em Doente Clínico Internado", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20203063, :description_tuss => "Pacientes Com Doença Isquêmica Do Coração, Hospitalizado, Até 8 Semanas De", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20203071, :description_tuss => "Pacientes Em Pós-Operatório De Cirurgia Cardíaca, Hospitalizado, Até 8 Semanas De", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20204027, :description_tuss => "Cardioversão Elétrica De Emergência", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20204035, :description_tuss => "Cardioversão Química De Arritmia Paroxísta Em Emergência", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20204043, :description_tuss => "Priapismo - Tratamento Não Cirúrgico", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 20204086, :description_tuss => "Terapia Oncológica Com Aplicação Intra-Arterial De Medicamentos, Em Regime De", :category_tuss => "Procedimentos Clínicos", :size => 0})
HealthTerminology.find_or_create_by({:code_tuss => 30101018, :description_tuss => "Abrasão Cirúrgica (Por Sessão)", :category_tuss => "Pele E Tecido Celular", :size => 1})
